kube-state-metrics:
  metricLabelsAllowlist:
   - pods=[*]
   - deployments=[app.kubernetes.io/name,app.kubernetes.io/component,app.kubernetes.io/instance]

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

    tsdb:
      outOfOrderTimeWindow: 30m

    enableOTLPReceiver: true

    additionalConfig:
      otlp:
        # This is the default naming for OTel Prometheus Exporter
        translationStrategy: UnderscoreEscapingWithSuffixes
        promoteResourceAttributes:
        - kn.service.name
        - kn.configuration.name
        - kn.revision.name
        - kn.route.name
        - kn.route.tag

        - service.instance.id
        - service.name
        - service.namespace
        - service.version

        - cloud.availability_zone
        - cloud.region
        - container.name

        - deployment.environment.name
        - k8s.cluster.name
        - k8s.container.name
        - k8s.cronjob.name
        - k8s.daemonset.name
        - k8s.deployment.name
        - k8s.job.name
        - k8s.namespace.name
        - k8s.pod.ip
        - k8s.pod.name
        - k8s.replicaset.name
        - k8s.statefulset.name
