{
 "title": "Knative Serving - Control Plane Efficiency",
 "description": "Knative Serving - Control Plane Efficiency",
 "tags": [ "Knative" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Namespace CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"knative-serving\"}[1m]))",
     "legendFormat": "knative-serving"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"istio-system\"}[1m]))",
     "legendFormat": "istio-system"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"kube-system\"}[1m]))",
     "legendFormat": "kube-system"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"kube-public\"}[1m]))",
     "legendFormat": "kube-public"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"knative-monitoring\"}[1m]))",
     "legendFormat": "knative-monitoring"
    }
   ]
  },
  {
   "title": "Namespace Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"knative-serving\"})",
     "legendFormat": "knative-serving"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"istio-system\"})",
     "legendFormat": "istio-system"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"kube-system\"})",
     "legendFormat": "kube-system"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"kube-public\"})",
     "legendFormat": "kube-public"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"knative-monitoring\"})",
     "legendFormat": "knative-monitoring"
    }
   ]
  },
  {
   "title": "Control Plane vs Data Plane CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace!~\"knative-serving|knative-monitoring|istio-system|kube-system|kube-public|^$\"}[1m]))",
     "legendFormat": "Data plane"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"knative-serving|knative-monitoring|istio-system|kube-system|kube-public\"}[1m]))",
     "legendFormat": "Control plane"
    }
   ]
  },
  {
   "title": "Control Plane vs Data Plane Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace!~\"knative-serving|knative-monitoring|istio-system|kube-system|kube-public|^$\"})",
     "legendFormat": "Data plane"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"knative-serving|knative-monitoring|istio-system|kube-system|kube-public\"})",
     "legendFormat": "Control plane"
    }
   ]
  }
 ]
}