{
 "title": "Knative Eventing - Source",
 "tags": [ "knative" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "ApiServerSource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Event Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserversource_event_count[1m]))"
    }
   ]
  },
  {
   "title": "Success Rate  (2xx Event)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserversource_event_count{response_code_class=\"2xx\"}[1m])) / sum(rate(apiserversource_event_count[1m]))"
    }
   ]
  },
  {
   "title": "Event Count by Response Code Class",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserversource_event_count[1m])) by (response_code_class)",
     "legendFormat": "{{response_code_class}}"
    }
   ]
  },
  {
   "title": "Failure Rate (non-2xx Event)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserversource_event_count{response_code_class!=\"2xx\"}[1m])) / sum(rate(apiserversource_event_count[1m])) OR on() vector(0)"
    }
   ]
  },
  { "title": "MT PingSource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Event Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pingsource_event_count[1m]))"
    }
   ]
  },
  {
   "title": "Success Rate  (2xx Event)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pingsource_event_count{response_code_class=\"2xx\"}[1m])) / sum(rate(pingsource_event_count[1m]))"
    }
   ]
  },
  {
   "title": "Event Count by Response Code Class",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pingsource_event_count[1m])) by (response_code_class)",
     "legendFormat": "{{response_code_class}}"
    }
   ]
  },
  {
   "title": "Failure Rate (non-2xx Event)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pingsource_event_count{response_code_class!=\"2xx\"}[1m])) / sum(rate(pingsource_event_count[1m])) OR on() vector(0)"
    }
   ]
  }
 ]
}