---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: controller
  name: controller
  namespace: knative-serving
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative-serving
  selector:
    matchLabels:
      app: controller
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: autoscaler
  name: autoscaler
  namespace: knative-serving
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative-serving
  selector:
    matchLabels:
      app: autoscaler
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: activator
  name: activator
  namespace: knative-serving
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative-serving
  selector:
    matchLabels:
      app: activator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: webhook
  name: webhook
  namespace: knative-serving
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative-serving
  selector:
    matchLabels:
      app: webhook
